name: Build and Test Pipeline

on:
  push:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      #  Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      #  Docker installieren
      - name: Install Docker
        run: |
         docker --version
      #  Docker-Image bauen  
      - name: Build Docker image
        run: docker build -t oldschool-demo-image .

      #  Container starten & Ausgabe testen 
      - name: Container starten & testen 
        run: | 
          output=$(docker run oldschool-demo-image) 
          echo "$output" 
          if [ "$output" != "OldSchool Gmbh - automatisch Build erfolgreich! (Isabella Moore)" ]; then 
          echo "Test fehlgeschlagen!" 
          exit 1 
          fi 
